config/routes.rb
Rails.application.routes.draw do

  root 'landing#home'
  get '/home', to: 'landing#home'
  get '/about', to: 'landing#about'
  get '/gallery', to: 'landing#gallery'
  get 'blender', to: 'landing#blender'
  get 'about(/:articles)', to: 'landing#about'
  get 'home(/:topicthreads)', to: 'landing#home'
  get 'home(/:topics)', to: 'landing#home'
  get 'home(/:branches)', to: 'landing#home'
  get 'home(/:blender)', to: 'landing#home'
  #get 'home(:profile)', to: 'users#show'

    devise_for :admins, controllers: {
               sessions: 'admins/sessions'
      }
  
        resources :topicthreads do
        resources :branches
     end
    

               resources :branches do
              resources :topics
             end

    devise_scope :admin do
    get "admin/home"=> "admin/sessions#home", :as => 'admin'
    resources :branches
    end

      devise_for :users do #controllers: {sessions: 'users/sessions'}
      #as :user do 
      #get 'signin', to: 'devise/sessions#new', as: :new_user_session
       #end
        #get 'user/subscription', to: 'devise/mailers#subscription', :as => 'user'
         resources :messages
           resources :comments
       
     end

    resources :topics do
       resources :messages
    end
    

    resources :subscriptions # do
      #post 'home(/:subsriptions)', to: 'landing#home'
   #end
 #get 'home/:subscription_email', to: 'subscription_mailer#subscription'
            
           # , path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }
    
  #get '/users' => 'landing#home', as: :user_root    #temporarily
 
  #devise_scope :user do
    #get 'login', to: 'landing#home' 
 #end

  resources :articles do
  	resources :comments
  end

    

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
 has_many :branches 

end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	mount_uploader :image, ImageUploader
end

app/models/branch.rb
class Branch < ApplicationRecord
	has_many :topics, :foreign_key => :branch_id, inverse_of: :branch

	belongs_to :topicthread
	
	belongs_to :admin
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  #validates :body, presence: true, length: {minimum: 2, maximum: 350}
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :topic
	belongs_to :article
	belongs_to :user

	
  #has_attached_file :image, :styles => {:thumb => '300x300#'}

#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/message.rb
class Message < ApplicationRecord
belongs_to :topic
	validates :body, presence: true, length: {minimum: 2, maximum: 350}
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	#before_save {self.email = self.email.downcase}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, #presence: true,
	         length: { minimum: 12, maximum: 255 },
	         format: {with: VALID_EMAIL_REGEX }#,
	         #uniqueness: { case_sensitive: false }
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :branch
	belongs_to :user, :optional => true
			
	has_many :messages, dependent: :destroy
	validates :body, :name, presence: true

	  mount_uploader :image, ImageUploader
  #serialize :images, JSON
	#attr_accessible  :image
 #validates_processing_of :image

#validates :image, presence: true, allow_nil: true
end

app/models/topicthread.rb
class Topicthread < ApplicationRecord
	has_many :branches, :foreign_key => :topicthread_id, inverse_of: :topicthread
        
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    #before_save { self.email = email.downcase }
    	#VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	#validates :email, presence: true, length: { maximum: 255 },
	                  #format: { with: VALID_EMAIL_REGEX },
	                  #uniqueness: { case_sensitive: false }
	#has_secure_password
	#validates :password, presence: true, length: { minimum: 6 }
  has_many :comments
  has_many :topics
  has_many :messages, through: :topics, dependent: :destroy 

  mount_uploader :image, ImageUploader

  validates_integrity_of :image
  validates_processing_of :image



end

app/controllers/topicthreads_controller.rb
class TopicthreadsController < ApplicationController

  before_action :set_topicthread, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_admin!, only: [:create, :edit, :update, :destroy]

  def index 
    @topicthreads = Topicthread.all
     
       
   
    
  end



	def new 
	 @topicthread = Topicthread.new

	end



	def show
	@topicthread = Topicthread.find(params[:id])
          @branch = Branch.new
    @branch.topicthread_id = @topicthread.id
    @branch.save
    end


      def create
    @topicthread = Topicthread.new(topicthread_params) 
       respond_to do |format|
      if @topicthread.save
        format.html { redirect_to @topicthread, notice: 'Topic thread was successfully created.' }
        format.json { render :show, status: :created, location: @topicthread }
      else
        format.html { render :new }
        format.json { render json: @topicthread.errors, status: :unprocessable_entity }
      end
    end
  end

 def update
    respond_to do |format|
      if @topicthread.update(topicthread_params) 
        format.html { redirect_to @topicthread, notice: 'Topic thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @topicthread }
      else
        format.html { render :edit }
        format.json { render json: @topicthread.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	@topicthread = Topicthread.find(params[:id])
    @topicthread.destroy 
    respond_to do |format|
      format.html { redirect_to topicthreads_url, notice: 'Topic thread was successfully deleted.' }
      format.json { head :no_content }
    end
     end

       private



     def set_topicthread
      @topicthread = Topicthread.find(params[:id])
    end

    def topicthread_params
      params.require(:topicthread).permit(:name)
    end




end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
    base_title = "3d News"
    if page_title.empty?
    	base_title
    else
     page_title + " | " + base_title 
    end
    end

    def gravatar_for(user, size)
         gravatar_id =  Digest::MD5.hexdigest(user.email)
           gravatar_url =  "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
      
       image_tag(gravatar_url, alt: user.name, class: "gravatar")
     end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/topicthreads_helper.rb
module TopicthreadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/topicthreads/_form.html.erb
<%= form_with(model: topicthread, local: true) do |form| %>
  <% if topicthread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topicthread.errors.count, "error") %> prohibited this thread from being saved:</h2>

      <ul>
      <% topicthread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :topicthread_name %>
    <%= form.text_field :name, id: :topicthread_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topicthreads/index.html.erb
<div class="center jumbotron">
<h1>3d Modeller News Forum</h1>
<p>Create your topics and answer to authors</p>


  <%= link_to "Home", home_path, class: "btn btn-lg btn-primary" %>
</div>


<p id="notice"><strong><%= "Forum Threads" %></strong></p>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
 <thead style= "background-color: rgba(255, 255, 255, 0)" >
    
    <% for topicthread in @topicthreads %><br />
     <%= link_to topicthread.name, topicthread_path(topicthread) %><br />


     
      </thead>
   
  <table width="100%" border="0" cellspacing="0" cellpadding="0">
   <thead style= "background-color: #379392" >
      <tr>
      <th>Branch</th>
      <th>Last topic</th>
      <th>By</th>
      <th>At</th>
      <th>Messages</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <tbody>
        <% for branch in topicthread.branches %>
    <tr>
       <td><%= link_to branch.title, branch_path(branch) %></td>
        <td><%= branch.topics.last.name %></td>
        <td><%= gravatar_for(branch.topics.last.user, 25) %></td>
        <td><%= branch.topics.last.created_at %></td>
        <td><%= pluralize(branch.topics.last.messages.count, "messages") %></td>
       <% end %>
    </tr>
  
    
</table>
  </tbody>
</table>
      
      <% end %>


<br>

app/views/topicthreads/new.html.erb
<h2>New Forum Thread</h2>

<%= render 'form', topicthread: @topicthread %>

<%= link_to 'Back', topicthreads_path %>

app/views/topicthreads/show.html.erb
<div class="center jumbotron">


  <%= link_to "Home", home_path, class: "btn btn-lg btn-primary" %>
</div>


<p id="notice"><%= @topicthread.name %></p>


  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead>
    <tr>
      <th>Branches</th>
      <th>Authors</th>
      <th>Last topic</th>
      <th>By</th>
      <th>At </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topicthread.branches.each do |branch| %>
       <tr>
        <td><%= link_to branch.title, branch_path(branch) %></td>
        <td><%= branch.topics.map{|topic| topic.user.name}.join(", ") %></td>
        <td><%= link_to branch.topics.last.name %></td>
         <td><%= branch.topics.last.user.name %></td>
          <td><%= branch.topics.last.created_at %></td>
               
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= link_to image_tag("planets_.jpg", alt: "space works") %>