config/routes.rb
Rails.application.routes.draw do

  root 'landing#home'
  get '/home', to: 'landing#home'
  get '/about', to: 'landing#about'
  get '/gallery', to: 'landing#gallery'
  get 'blender', to: 'landing#blender'
  get 'about(/:articles)', to: 'landing#about'
  get 'home(/:topicthreads)', to: 'landing#home'
  get 'home(/:topics)', to: 'landing#home'
  get 'home(/:branches)', to: 'landing#home'
  get 'home(/:blender)', to: 'landing#home'
  #get 'home(:profile)', to: 'users#show'

    devise_for :admins, controllers: {
               sessions: 'admins/sessions'
      }
  
        resources :topicthreads do
        resources :branches
     end
    

               resources :branches do
              resources :topics
             end

    devise_scope :admin do
    get "admin/home"=> "admin/sessions#home", :as => 'admin'
    resources :branches
    end

      devise_for :users do #controllers: {sessions: 'users/sessions'}
      #as :user do 
      #get 'signin', to: 'devise/sessions#new', as: :new_user_session
       #end
        #get 'user/subscription', to: 'devise/mailers#subscription', :as => 'user'
         resources :messages
           resources :comments
       
     end

    resources :topics do
       resources :messages
    end
    

    resources :subscriptions # do
      #post 'home(/:subsriptions)', to: 'landing#home'
   #end
 #get 'home/:subscription_email', to: 'subscription_mailer#subscription'
            
           # , path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }
    
  #get '/users' => 'landing#home', as: :user_root    #temporarily
 
  #devise_scope :user do
    #get 'login', to: 'landing#home' 
 #end

  resources :articles do
  	resources :comments
  end

    

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
 has_many :branches 

end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	mount_uploader :image, ImageUploader
end

app/models/branch.rb
class Branch < ApplicationRecord
	has_many :topics, :foreign_key => :branch_id, inverse_of: :branch

	belongs_to :topicthread
	
	belongs_to :admin
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  #validates :body, presence: true, length: {minimum: 2, maximum: 350}
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :topic
	belongs_to :article
	belongs_to :user

	
  #has_attached_file :image, :styles => {:thumb => '300x300#'}

#validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/message.rb
class Message < ApplicationRecord
belongs_to :topic
	validates :body, presence: true, length: {minimum: 2, maximum: 350}
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	#before_save {self.email = self.email.downcase}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, #presence: true,
	         length: { minimum: 12, maximum: 255 },
	         format: {with: VALID_EMAIL_REGEX }#,
	         #uniqueness: { case_sensitive: false }
end

app/models/topic.rb
class Topic < ApplicationRecord
	belongs_to :branch
	belongs_to :user, :optional => true
			
	has_many :messages, dependent: :destroy
	validates :body, :name, presence: true

	  mount_uploader :image, ImageUploader
  #serialize :images, JSON
	#attr_accessible  :image
 #validates_processing_of :image

#validates :image, presence: true, allow_nil: true
end

app/models/topicthread.rb
class Topicthread < ApplicationRecord
	has_many :branches, :foreign_key => :topicthread_id, inverse_of: :topicthread
        
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    #before_save { self.email = email.downcase }
    	#VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	#validates :email, presence: true, length: { maximum: 255 },
	                  #format: { with: VALID_EMAIL_REGEX },
	                  #uniqueness: { case_sensitive: false }
	#has_secure_password
	#validates :password, presence: true, length: { minimum: 6 }
  has_many :comments
  has_many :topics
  has_many :messages, through: :topics, dependent: :destroy 

  mount_uploader :image, ImageUploader

  validates_integrity_of :image
  validates_processing_of :image



end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
 before_action :set_topic, only: [:create, :show, :edit, :update]
 #before_action :set_branch, only: [:create]
before_action :authenticate_user!, only: [:create, :edit, :update]
before_action :authenticate_admin!, only: [:destroy]


	def index
		@topics = Topic.all
    end

	def show 

@topic = Topic.find(params[:id])
   	@message = Message.new
  	@message.topic_id = @topic.id
  	@message.save
    @topic.messages.count
    if @topic.messages.count > 0
    @topic.messages.last.created_at
  end
  

	end

  
   def new
  @topic = Topic.new
        


  end
    


def create
  @topic = current_user.topics.build(topic_params) || @topic = @branch.topics.build(topic_params)
    @topic.user_id = @topic.user.id
  @topic.branch_id = params[:branch_id] || @topic.branch_id = session[:branch_id] 
   if !user_signed_in?
  redirect_to new_user_session_path
   end
 if @topic.save
  flash[:success] = 'Your topic is saved'
  redirect_to branch_topics_path(@topic.branch_id)
#format.html { redirect_to @topic.branch_id, notice: 'Topic saved.' }
        #format.json { render :show, status: :created, location: @branch }
   else
    redirect_to topics_path
   end
  
end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params) 
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy

  	@topic = Topic.find(params[:id])
     @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully deleted.' }
      format.json { head :no_content }
    end

     end

         def topic_params
      params.require(:topic).permit(:name, :body, :branch_id, :image, :image_cache)
    end

       private

    def set_topic
      @topic = Topic.find_by_id(params[:id])
    end

  # def set_branch
    # @branch = Branch.find_by(session[:branch_id])
  # end


end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
    base_title = "3d News"
    if page_title.empty?
    	base_title
    else
     page_title + " | " + base_title 
    end
    end

    def gravatar_for(user, size)
         gravatar_id =  Digest::MD5.hexdigest(user.email)
           gravatar_url =  "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
      
       image_tag(gravatar_url, alt: user.name, class: "gravatar")
     end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/topicthreads_helper.rb
module TopicthreadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/topics/_form.html.erb
 <%= form_for [ @branch, @topic ] do |form| %> 


  <div class="field">
    <%= form.label :topic_name %>
    <%= form.text_field :name, id: :topic_name %>
  </div>

    <div class="field">
    <%= form.label :author_name %>
    <%= current_user.name %>
  </div>

  <div class="field">
    <%= form.label :your_text %>
    <%= form.text_area :body, id: :topic_body %>
  </div>

   <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>




<% end %>

app/views/topics/_imageform.html.erb
<%= form_for [ @branch, @topic ], html: { multipart: true } do |f| %>
  <p>
    <label>Upload image</label>
    <%= image_tag(@topic.image_url) if @topic.image? %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image %>
  </p>
<% end %>

app/views/topics/_message.html.erb
<div>
<h6>Message by <%= message.author %></h6>
<h7 class="message"><%= message.body %></h7>
</div>

app/views/topics/edit.html.erb
<h1>Editing Your Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<div class="center jumbotron">
<h1>3d Modeller News Forum</h1>
<p>Create your topics and answer to authors</p>


  <%= link_to "Home", home_path, class: "btn btn-lg btn-primary" %>
</div>


<p id="notice"><%= "All topics overall" %></p>


  <table width="100%" border="0" cellspacing="0" cellpadding="0">
  <thead style= "background-color: #379392" >
    <tr>
      <th>Topics</th>
      <th>Authors</th>
      <th>Messages</th>
      <th>Last message</th>
      <th>By</th>
      <th>At </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
       <tr>
        <td><%= link_to topic.name, topic_path(topic) %></td>
        <td><%= topic.user.name %></td>
        <td><%= pluralize(topic.messages.count, "messages") %></td>
         <% if topic.messages.count > 0 %>
          <td><%= topic.messages.last.body %></td>
          <td><%= topic.messages.last.author %></td>
          <td><%= topic.messages.last.created_at %></td> 
         <% end %>   
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to image_tag("planets_.jpg", alt: "space works",  :size => "1100x450") %>

app/views/topics/new.html.erb
<h2>New Forum Topic</h2>

<%= render 'form', topic: @topic %>
<%= render 'imageform', topic: @topic %>
<%= link_to 'Back', topics_path(@topics) %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="gravatar">
	<%= gravatar_for(@topic.user,40) %>
		<div class="img img-responsive">
	</div>


<p>
 <strong><%= @topic.name %></strong>  
</p>

<p>
   <%= @topic.body %>
</p>

<p>
<strong>Author:</strong> 
<%= @topic.user.name %>
</p>

<h3>Messages</h3>
<%= render partial: 'topics/message', collection: @topic.messages %>
<%= render partial: 'messages/form' %>

<%= image_tag(@topic.image.url, alt: 'Image') if @topic.image? %>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Destroy', topic_path(@topic), method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', topics_path %>